services:
  - type: web
    name: strapi-agile-peak
    env: node
    plan: free
    region: ohio
    repo: https://github.com/markhillard/strapi-agile-peak.git
    branch: master
    buildCommand: yarn install && yarn build
    startCommand: strapi start
    healthCheckPath: /
    envVars:
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_ACCESS_SECRET
        sync: false
      - key: AWS_BUCKET
        sync: false
      - key: AWS_REGION
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-agile-peak
          property: connectionString
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_REPLY_TO
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: ^18.19.0
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false

databases:
  - name: strapi-agile-peak
    plan: free
    region: ohio
